### ISSUE TITLE
0.5.1 uses request@2.29.0 with qs@0.6.6 which has security vulnerabilities

### ISSUE THREAD

**Issue by AlexClineBB** [normanjoyner/chef-api#24]
chef-api@0.5.1 > request@2.29.0 > qs@0.6.6

Need to update dependency to request@2.40.0 at least.

**Comment by normanjoyner** [comment]
can hopefully make time this week to fix this

**Comment by normanjoyner** [comment]
updating request to 2.61.0 updated qs to 4.0.0

**Comment by normanjoyner** [comment]
released in chef-api@0.5.2
